services:
  backend:
    build:
      context: ./backend
      dockerfile: Docker_Nest
    container_name: backend
    restart: always
    ports:
      - "5000:5000"
    # volumes:
    #   - ./backend:/app
    networks:
      - app-network

  frontend:
    # platform: linux/amd64
    build:
      context: ./frontend
      dockerfile: Docker_React
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    # volumes:
    #   - ./frontend:/app
    depends_on:
      - backend
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
